"""auto gen

Revision ID: a14abadd7a65
Revises: bdb5c3854fb3
Create Date: 2023-01-30 11:55:19.067918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14abadd7a65'
down_revision = 'bdb5c3854fb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
